langlab/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path  # For django versions from 2.0 and up

urlpatterns = [
    path('', include('main.urls'), {'lang': 'es', 'section': 'home'}),
    path('admin/', admin.site.urls),
]


# Add the Debug Toolbar's URLs
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

main/urls.py
from django.urls import path
from .views import Index
from django.views.generic import RedirectView


# App Namespace
app_name = 'main'

urlpatterns = [
    path('<str:lang>/<str:section>', Index.as_view(), name='index'),
    #path('<str:lang>/<str:section>', RedirectView.as_view(), name='index'),
]

main/models.py
from django.db import models


class Locations(models.Model):

    '''
    Index page contents locations
    '''
    location = models.CharField(max_length=15, primary_key=True)

    def __str__(self):
        return self.location


class Languages(models.Model):
    '''
    '''
    language = models.CharField(max_length=2, primary_key=True)

    def __str__(self):
        return self.language


class Menus(models.Model):
    '''
    Menu: label
    path: url
    '''
    menu = models.CharField(max_length=15)
    urlpath = models.CharField(max_length=15)
    # field order should respect the sequentiality given in Languages
    # en = models.CharField(max_length=15)
    # it = models.CharField(max_length=15)
    # es = models.CharField(max_length=15)
    # fr = models.CharField(max_length=15)
    # It’s suggested, but not required, that the name of a ForeignKey field
    # be the name of the model, lowercase
    location = models.ForeignKey(Locations, on_delete=models.CASCADE)
    language = models.ForeignKey(Languages, on_delete=models.CASCADE)

    def __str__(self):
        return self.menu


class Disclaimers(models.Model):
    '''
    '''
    disclaimer = models.CharField(max_length=50, primary_key=True)
    # en = models.CharField(max_length=50)
    # it = models.CharField(max_length=50)
    # es = models.CharField(max_length=50)
    # fr = models.CharField(max_length=50)
    # It’s suggested, but not required, that the name of a ForeignKey field
    # be the name of the model, lowercase
    location = models.ForeignKey(Locations, on_delete=models.CASCADE)
    language = models.ForeignKey(Languages, on_delete=models.CASCADE)

    def __str__(self):
        return self.disclaimer

main/forms.py
from django import forms
'''
https://docs.djangoproject.com/en/3.0/ref/forms/fields/

required: To specify that a field is not required, pass required=False to the Field constructor:
label: lets you specify the “human-friendly” label for this field. This is used when the Field is displayed in a Form.

'''

class ContactForm(forms.Form):

    sender = forms.EmailField(min_length=5, max_length=20, label="email", required=True)
    message = forms.CharField(min_length=10, max_length=250, strip=True, label="message", required=False)

main/views.py
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404
from django.views import View
from django.views.generic import FormView, ListView
from django.views.generic.detail import SingleObjectMixin
from .models import Languages, Menus
from .forms import ContactForm
from django.core.mail import send_mail


class LayoutListView(ListView):
    # TBD
    #

    context_object_name = 'menu_list'

    def get_template_names(self, **kwargs):
        template_name = 'main/' + self.kwargs['section'] + '.html'
        return template_name

    def get_queryset(self):
        self.lang = get_object_or_404(Languages, language=self.kwargs['lang'])
        return Menus.objects.filter(language=self.lang, location='navbar')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        # Generally, get_context_data will merge the context data of all parent classes
        # with those of the current class
        context['lang_list'] = Languages.objects.all()
        context['selflang'] = self.lang
        context['selfsection'] = self.kwargs['section']
        # TBD : really need here?
        context['form'] = ContactForm()
        return context


class ContactUsMix(SingleObjectMixin, FormView):

    template_name = 'main/contactus.html'
    form_class = ContactForm
    model = Menus

    def post(self, request, *args, **kwargs):

        if not request.user.is_authenticated:
            return HttpResponseForbidden()

        self.object = self.get_object()
        return super().post(request, *args, **kwargs)


class Index(View):

    def get(self, request, *args, **kwargs):
        view = LayoutListView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = ContactUsMix.as_view()
        return view(request, *args, **kwargs)

main/templates/main/aboutus.html
{% extends 'main/home.html' %}

main/templates/main/contactus.html
{% extends 'main/layout.html' %}

{% block centralcolumncontent %}
    <!-- Basic default template -->
    <!--div class="card">
      <h2>{{section}}</h2>
      <h5>Title description, Dec 17, 2019</h5>
        <form action="main/contactus/" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
    </div-->

    <!-- My template-->
    <div class="card">
        <h2>{{section}}</h2>
        <h5>Title description, Dec 17, 2019</h5>

        <div class="container">
          <form action="main/home.html">
          <div class="row">
            <div class="col-25">
              <label for="fname">First Name</label>
            </div>
            <div class="col-75">
              <input type="text" id="fname" name="firstname" placeholder="Your name..">
            </div>
          </div>
          <div class="row">
            <div class="col-25">
              <label for="lname">Last Name</label>
            </div>
            <div class="col-75">
              <input type="text" id="lname" name="lastname" placeholder="Your last name..">
            </div>
          </div>
          <div class="row">
            <div class="col-25">
              <label for="country">Country</label>
            </div>
            <div class="col-75">
              <select id="country" name="country">
                <option value="australia">Colombia</option>
                <option value="canada">Peru</option>
                <option value="usa">Cile</option>
              </select>
            </div>
          </div>
          <div class="row">
            <div class="col-25">
              <label for="subject">Subject</label>
            </div>
            <div class="col-75">
              <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>
            </div>
          </div>
          <div class="row">
            <input type="submit" value="Submit">
          </div>
          </form>
        </div>
    </div>
{% endblock %}

main/templates/main/home.html
{% extends 'main/layout.html' %}

{% block centralcolumncontent %}

  <div class="card">
    <h2>{{section}}</h2>
    <h5>Title description, Dec 7, 2017</h5>
    <div class="fakeimg" style="height:200px;">Image</div>
    <p>Some text..</p>
    <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
  </div>

  <div class="card">
    <h2>TITLE HEADING</h2>
    <h5>Title description, Sep 2, 2017</h5>
    <div class="fakeimg" style="height:200px;">Image</div>
    <p>Some text..</p>
    <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
  </div>

{% endblock %}

main/templates/main/layout.html
<!DOCTYPE html>

{% load static %}

<html>
	<head>
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	</head>
<body>

<div class="topnav">
    {% block navigation %}
        {% for menu in menu_list %}
        <a href="{% url 'main:index' lang=selflang section=menu.urlpath%}"
           class="list-group-item list-group-item-action text-body text-uppercase">{{ menu | capfirst }}</a>
    {% endfor %}
    {% endblock %}
</div>

<div class="header">
	<div class="row">
		<div class="col" style="padding-left: 500px;float: left;">
			<!--img src="logo.jpeg" alt="logo" -->
            <img src="{% static "imag/logo.jpeg" %}" alt="My image">
		</div>
		<div class="col" style="float: left;">
			<h1 style="font-family: serif;font-weight: lighter"> Lang</h1>
		</div>
		<div class="col" style="float: left;">
			<h1 style="font-family: sans-serif;"> Lab</h1>
		</div>
		<div class="col" style="float: left;">
			<h1 style="font-family: serif;font-weight: lighter;">
			{
				<div class="dropdown">
  				<button class="dropbtn">{{selflang | capfirst}}</button>
  					<div class="dropdown-content">
                        {% for langvar in lang_list %}
                            {% if langvar != selflang  %}
                            <a href="{% url 'main:index' lang=langvar section=selfsection%}">{{ langvar | capfirst }}</a>
                            {% endif %}
                        {% endfor %}
  					</div>
				</div> 
			}</h1>
		</div>
</div>

<div class="row">

  <div class="leftcolumn">
    <div class="card">
      <h2>TITLE HEADING</h2>
      <h5>Title description, Dec 7, 2017</h5>
      <div class="fakeimg" style="height:200px;">Image</div>
      <p>Some text..</p>
      <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
    </div>
    <div class="card">
      <h2>TITLE HEADING</h2>
      <h5>Title description, Sep 2, 2017</h5>
      <div class="fakeimg" style="height:200px;">Image</div>
      <p>Some text..</p>
      <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
    </div>
  </div>

  <div class="centralcolumn">
      {% block centralcolumncontent %}
      {% endblock%}
  </div>

  <div class="rightcolumn">
    <div class="card">
      <h2>About Me</h2>
      <div class="fakeimg" style="height:100px;">Image</div>
      <p>Some text about me in culpa qui officia deserunt mollit anim..</p>
    </div>
    <div class="card">
      <h3>Popular Post</h3>
      <div class="fakeimg"><p>Image</p></div>
      <div class="fakeimg"><p>Image</p></div>
      <div class="fakeimg"><p>Image</p></div>
    </div>
    <div class="card">
      <h3>Follow Me</h3>
      <p>Some text..</p>
    </div>
  </div>
</div>

<div class="footer">
  <h2>Footer</h2>
</div>

</body>
</html>

main/templates/main/services.html
{% extends 'main/home.html' %}